default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password:
  pool: 5

development:
  <<: *default
  database: agendaweb_development

test:
  <<: *default
  database: agendaweb_test